project_name: sling

before:
  hooks:
    - go mod edit -dropreplace='github.com/flarco/g' go.mod
    - go mod edit -dropreplace='github.com/slingdata-io/sling' go.mod
    - go mod edit -droprequire='github.com/slingdata-io/sling' go.mod
    - go mod tidy

builds:
  - main: ./cmd/sling
    env:
      - CGO_ENABLED=1  # Enable CGO
    tags:
      - fts5
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-X 'github.com/slingdata-io/sling-cli/core.Version={{.Version}}'"

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .Runtime.Goos }}.{{ .Runtime.Goarch }}.checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: yokofly
    name: sling-cli
